name: nasa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  share: ^2.0.4
  pull_to_refresh: ^2.0.0
  equatable: ^2.0.2
  flutter_bloc: ^7.0.0
  mockito: ^5.0.9
  dartz: ^0.10.0-nullsafety.2
  connectivity: ^3.0.6
  get_it: ^7.1.3
  seafarer: ^0.1.0
  shimmer: ^2.0.0
  font_awesome_flutter: ^9.0.0
  animations: ^2.0.0
  http: ^0.13.3
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.0.0
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.0

  # Firebase
  # firebase_auth: ^1.2.0
  # google_sign_in: ^5.0.4
  # cloud_firestore: ^2.2.0 
  # firebase_core: ^1.2.0
  # firebase_messaging: ^10.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/nasa_app_logo.png"    

flutter:

  assets:
    - assets/

  uses-material-design: true
